### PR TITLE
fix(chrome): align the max payload size with the spec

### LINKED ISSUE #522: Unable to load a large content
## Environment

| Component | Version
|-|-
| Node.js						| v16.19.0
| Client (Chrome/Chromium/...)	| Chrome/Chromium
| OS running Node.js			| MacOS
| OS running the client			| MacOS
| chrome-remote-interface		| v0.32.0

Is the client running in a container? NO

## Description
Unable to retrieve a response body that is greater than 100MB. The maximum size of a message that can be sent through Chrome DevTools is 256 MB: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/devtools_http_handler.cc;l=90?q=kSendBufferSizeForDevTools&ss=chromium

## Steps to reproduce
1. Server an `index.html` file that loads a JSON greater than 100MB in size. Example:
<details>
  <summary>index.js</summary>
  
 ```js
const express = require('express');
const app = express();

app.get('/', (_, res) => res.sendFile('index.html', { root: __dirname }));

app.get('/api/keys', (_, res) =>
  res.json({
    keys: Array(1000)
      .fill(0)
      .map((_noop, idx) => ({
        key: randomBytes(100000).toString('hex'),
        id: idx
      }))
  })
);

app.listen(3000, () => {
  console.log("Server started on port 3000");
});
```
</details>

<details>
  <summary>index.html</summary>
  
 ```js
<p id="result"></p>
<script>
  const result = document.querySelector("#result");

  fetch("/api/keys")
    .then((response) => response.json())
    .then((data) => {
      result.innerHTML = `Found ${data.keys.length} keys`
    });
</script>

```
</details>

2. Open the root page and initiate the listening process for incoming requests.
```js
const maxSize = 256 * 1024 * 1204;
const client = await CDP();

client.Network.enable({
    maxResourceBufferSize: maxSize,
    maxTotalBufferSize: maxSize,
});

let targetRequestId;

client.Network.on('requestWillBeSent', async ({request, requestId}) => {
    if (request.url.includes('/api/keys')) {
        targetRequestId = requestId;
    }
});
client.Network.on('loadingFinished', async ({requestId}) => {
    try {
        if (!targetRequestId || targetRequestId !== requestId) {
            return;
        }
        console.log(`Loading the content for ${requestId}`);
        const res = await client.Network.getResponseBody({requestId});
        console.log(`Content loaded: ${Buffer.from(res.body).byteLength} bytes`);
    } catch (e) {
        console.error('Unable to load the content due to the error:');
        console.error(e);
    }
});
client.once('ready', () => client.Page.navigate({url: 'http://localhost:3000'}));
client.once('disconnect', () => console.log('The socket disconnected.'));
```

## Actual behavior
The connection has been unexpectedly terminated, resulting in the inability to retrieve the content.

For details please refer to https://github.com/puppeteer/puppeteer/issues/4543 and https://github.com/NeuraLegion/cypress-har-generator/issues/177

### PR DESCRIPTION
**Pull request by derevnjuk**
closes #522

### CODE REVIEW

File: lib/chrome.js [hunk 1]
```diff
@@ -220,7 +220,11 @@ class Chrome extends EventEmitter {
                 if (this.secure) {
                     this.webSocketUrl = this.webSocketUrl.replace(/^ws:/i, 'wss:');
                 }
-                this._ws = new WebSocket(this.webSocketUrl);
+                this._ws = new WebSocket(this.webSocketUrl, [], {
+                    maxPayload: 256 * 1024 * 1024,
+                    perMessageDeflate: false,
+                    followRedirects: true,
```
Comment (cyrus-and) [inline lib/chrome.js:226]: Why has `followRedirects` been set to `true`?

**Comment by cyrus-and** [comment]
Thanks for the quality contribution.

File: lib/chrome.js (hunk 1 above)
Comment (derevnjuk) [reply lib/chrome.js:226]: Just in case someone is using a reverse proxy or some other intermediary in front of Chrome.
